// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tprhhqlgtzezzkvryeze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcmhocWxndHplenprdnJ5ZXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDI5NjgsImV4cCI6MjA2NjAxODk2OH0.lxujURY8KP6KuWxLigpsYyzeXhiVtXNZEuNb9xKLcnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);